export enum TaxTrigger {
  SALE = 'SALE',
  SALE_RETURN = 'SALE_RETURN',
  CREDIT_NOTE = 'CREDIT_NOTE',
  DELIVERY = 'DELIVERY',
  PURCHASE_RETURN = 'PURCHASE_RETURN',
  WRITE_OFF = 'WRITE_OFF',
  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT'
}
