export enum MovementType {
  SALE = 'SALE',
  SALE_VOID = 'SALE_VOID',
  CUSTOMER_RETURN = 'CUSTOMER_RETURN',
  SUPPLIER_RETURN = 'SUPPLIER_RETURN',
  ADJUSTMENT = 'ADJUSTMENT',
  TRANSFER_IN = 'TRANSFER_IN',
  TRANSFER_OUT = 'TRANSFER_OUT',
  WRITE_OFF = 'WRITE_OFF',
  PURCHASE_RECEIVED = 'PURCHASE_RECEIVED'
}
